import type { RegistryItem } from "shadcn/registry";

export const defaultStyle: RegistryItem = {
	name: "index",
	type: "registry:style",
	dependencies: ["clsx", "tailwind-merge", "tailwind-variants"],
	registryDependencies: ["cn", "theme", "context", "resolve-classname"],
	files: [],
	cssVars: {
		light: {
			"color-primary-50": "var(--color-purple-50)",
			"color-primary-100": "var(--color-purple-100)",
			"color-primary-200": "var(--color-purple-200)",
			"color-primary-300": "var(--color-purple-300)",
			"color-primary-400": "var(--color-purple-400)",
			"color-primary-500": "var(--color-purple-500)",
			"color-primary-600": "var(--color-purple-600)",
			"color-primary-700": "var(--color-purple-700)",
			"color-primary-800": "var(--color-purple-800)",
			"color-primary-900": "var(--color-purple-900)",
			"color-primary-950": "var(--color-purple-950)",

			"color-default-0": "var(--color-neutral-0)",
			"color-default-50": "var(--color-neutral-50)",
			"color-default-100": "var(--color-neutral-100)",
			"color-default-200": "var(--color-neutral-200)",
			"color-default-300": "var(--color-neutral-300)",
			"color-default-400": "var(--color-neutral-400)",
			"color-default-500": "var(--color-neutral-500)",
			"color-default-600": "var(--color-neutral-600)",
			"color-default-700": "var(--color-neutral-700)",
			"color-default-800": "var(--color-neutral-800)",
			"color-default-900": "var(--color-neutral-900)",
			"color-default-950": "var(--color-neutral-950)",
			"color-default-1000": "var(--color-neutral-1000)",
		},
		dark: {
			"color-primary-50": "var(--color-purple-950)",
			"color-primary-100": "var(--color-purple-900)",
			"color-primary-200": "var(--color-purple-800)",
			"color-primary-300": "var(--color-purple-700)",
			"color-primary-400": "var(--color-purple-600)",
			"color-primary-500": "var(--color-purple-500)",
			"color-primary-600": "var(--color-purple-400)",
			"color-primary-700": "var(--color-purple-300)",
			"color-primary-800": "var(--color-purple-200)",
			"color-primary-900": "var(--color-purple-100)",
			"color-primary-950": "var(--color-purple-50)",

			"color-default-0": "var(--color-neutral-0)",
			"color-default-50": "var(--color-neutral-50)",
			"color-default-100": "var(--color-neutral-100)",
			"color-default-200": "var(--color-neutral-200)",
			"color-default-300": "var(--color-neutral-300)",
			"color-default-400": "var(--color-neutral-600)",
			"color-default-500": "var(--color-neutral-500)",
			"color-default-600": "var(--color-neutral-400)",
			"color-default-700": "var(--color-neutral-300)",
			"color-default-800": "var(--color-neutral-200)",
			"color-default-900": "var(--color-neutral-100)",
			"color-default-950": "var(--color-neutral-50)",
			"color-default-1000": "var(--color-neutral-0)",
		},
	},
};
