import { exec } from "node:child_process";
import * as fs from "node:fs/promises";
import path from "node:path";
import { rimraf } from "rimraf";
import { type Registry, registryItemSchema } from "shadcn/registry";
import { z } from "zod";

import { examples } from "../registry/registry-examples";
import { lib } from "../registry/registry-lib";
import { styles } from "../registry/registry-styles";
import { ui } from "../registry/registry-ui";
const DEPRECATED_ITEMS: string[] = [];

const registry = {
	name: "annui",
	homepage: "https://annui.org",
	items: z.array(registryItemSchema).parse(
		[...styles, ...lib, ...ui, ...examples].filter((item) => {
			return !DEPRECATED_ITEMS.includes(item.name);
		}),
	),
} satisfies Registry;

async function buildRegistryIndex() {
	let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`;
	for (const item of registry.items) {
		const resolveFiles = item.files?.map((file) => `${file.path}`);
		if (!resolveFiles) {
			continue;
		}

		const componentPath = item.files?.[0]?.path
			? `@/${item.files[0].path}`
			: "";

		index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${item.files?.map((file) => {
			const filePath = `${typeof file === "string" ? file : file.path}`;
			const resolvedFilePath = path.resolve(filePath);
			return typeof file === "string"
				? `"${resolvedFilePath}"`
				: `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ""}"
    }`;
		})}],
    component: ${
			componentPath
				? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    })`
				: "null"
		},
    meta: ${JSON.stringify(item.meta)},
  },`;
	}

	index += `
}`;

	// Write style index.
	rimraf.sync(path.join(process.cwd(), "__registry__/index.tsx"));
	await fs.writeFile(path.join(process.cwd(), "__registry__/index.tsx"), index);
}

async function buildRegistryJsonFile() {
	// 1. Fix the path for registry items.
	const fixedRegistry = {
		...registry,
		items: registry.items.map((item) => {
			const files = item.files?.map((file) => {
				return {
					...file,
					path: `${file.path}`,
				};
			});

			return {
				...item,
				files,
			};
		}),
	};

	// 2. Write the content of the registry to `registry.json`
	rimraf.sync(path.join(process.cwd(), "registry.json"));
	await fs.writeFile(
		path.join(process.cwd(), "registry.json"),
		JSON.stringify(fixedRegistry, null, 2),
	);
}

async function buildRegistry() {
	return new Promise((resolve, reject) => {
		const process = exec("pnpm shadcn:build");

		process.on("exit", (code) => {
			if (code === 0) {
				resolve(undefined);
			} else {
				reject(new Error(`Process exited with code ${code}`));
			}
		});
	});
}

try {
	console.log("🗂️ Building registry/__index__.tsx...");
	await buildRegistryIndex();
	console.log("✅ Registry index built successfully");

	console.log("💅 Building registry.json...");
	await buildRegistryJsonFile();
	console.log("✅ Registry JSON file built successfully");

	console.log("🏗️ Building registry...");
	await buildRegistry();
	console.log("✅ Registry build completed");
} catch (error) {
	console.error("❌ Build failed with error:");
	console.error(error);
	if (error instanceof Error) {
		console.error("Error stack:", error.stack);
	}
	process.exit(1);
}
